Repository likelion-inha-hackathon-2/Meong-Signal-FE, pull requests merged in 2024-07, with the labels that each got.

#7 feat: Layout, Footer, Header 컴포넌트 구현
  README.md
  package-lock.json
  package.json
  src/App.jsx
  src/assets/icons/icon-chat.png
  src/assets/icons/icon-main.png
  src/assets/icons/icon-map.png
  src/assets/icons/icon-user.png
  src/assets/icons/icon-walk.png
  src/components/Footer/Footer.jsx
  src/components/Header/Header.jsx
  src/components/Layout/Layout.jsx
  src/pages/Home.jsx
Labels: 🎨 design, 💡 feat

#12 Feat: #6 버튼,인풋,이미지 컴포넌트 구현
  src/components/Button/Button.jsx
  src/components/Image/Image.jsx
  src/components/Input/Input.jsx
Labels: 💡 feat

#18 feat: #16 Map 컴포넌트 만들기
  .gitignore
  eslint.config.mjs
  package-lock.json
  package.json
  src/App.jsx
  src/apis/kakaoApi.js
  src/components/Map/Map.jsx
  src/hooks/useKakaoMap.js
  src/pages/Map/MapInfo.jsx
  src/pages/Map/MapStatus.jsx
  webpack.config.js
Labels: ⚙️ chore, 💡 feat

#21 feat: 로그인 및 회원가입에 필요한 토큰 인증 처리 및 라우터 수정
  src/App.jsx
  src/apis/authApi.js
  src/components/Button/Button.jsx
  src/components/Input/Input.jsx
  src/hooks/useForm.js
  src/index.css
  src/pages/Login.jsx
Labels: 🔧 refactor, 💡 feat

#23 feat: #22 내 정보 확인 및 강아지 등록 페이지 구현
  public/index.html
  src/App.jsx
  src/apis/authApi.js
  src/assets/images/add-dog.png
  src/components/Button/Button.jsx
  src/components/Footer/Footer.jsx
  src/components/Info/DogInfo.jsx
  src/components/Input/Input.jsx
  src/components/Layout/Layout.jsx
  src/hooks/useForm.js
  src/pages/Login.jsx
  src/pages/MyInfo/MyInfoMain.jsx
  src/pages/MyInfo/RegisterDog.jsx
Labels: 🎨 design, 🔧 refactor, 💡 feat

#24 refactor: #16 지도 불러올 때 swagger 위도 경도 변환 함수 사용하여 현재 위치 받아오도록 수정
  src/apis/kakaoApi.js
  src/pages/Map/MapInfo.jsx
  src/pages/Map/MapStatus.jsx
Labels: 🔧 refactor

#25 feat: 강아지 상태 변경, 심심한 상태의 강아지를 지도에 표시하는 커스텀 오버레이 추가
  package-lock.json
  package.json
  public/index.html
  src/App.jsx
  src/apis/authApi.js
  src/apis/getBoringDogs.js
  src/apis/kakaoApi.js
  src/assets/images/status-b.png
  src/assets/images/status-change.png
  src/assets/images/status-r.png
  src/assets/images/status-w.png
  src/components/Info/DogInfo.jsx
  src/components/Input/Input.jsx
  src/components/ToolTip/ToolTip.jsx
  src/hooks/useKakaoMap.js
  src/index.js
  src/pages/Map/MapInfo.jsx
  src/pages/MyInfo/MyInfoEdit.jsx
  src/pages/MyInfo/MyInfoMain.jsx
  src/pages/MyInfo/RegisterDog.jsx
  webpack.config.js
Labels: ⚙️ chore, 🎨 design, 🔧 refactor, 💡 feat

#26 fix: #22 내 정보 수정 페이지에서 프로필 사진 업로드 수정
  src/apis/authApi.js
  src/pages/MyInfo/MyInfoEdit.jsx
Labels: 🐛 bug fix, 🎨 design

#28 Feat: #15 회원가입 페이지 1,2 페이지 구현
  public/index.html
  src/assets/apis/authApi.js
  src/assets/hooks/useForm.jsx
  src/assets/icons/icon-camera.png
  src/assets/icons/icon-main-image.png
  src/assets/icons/icon-user-image.png
  src/pages/SignUp/SignUp1.jsx
  src/pages/SignUp/SignUp2.jsx
Labels: 💡 feat

#31 feat: #22 강아지 사진 등록 추가 구현
  package-lock.json
  package.json
  src/assets/images/add-dog.png
  src/pages/MyInfo/MyInfoEdit.jsx
  src/pages/MyInfo/MyInfoMain.jsx
  src/pages/MyInfo/RegisterDog.jsx
  src/pages/SignUp/SignUp1.jsx
  src/pages/SignUp/SignUp2.jsx
Labels: ⚙️ chore, 🎨 design, 🔧 refactor, 💡 feat

#32 feat: 로그인 페이지 라우팅 및 로고 추가
  src/assets/images/logo.png
  src/pages/Login.jsx
Labels: 🎨 design, 🔧 refactor

#33 fix: #22 강아지 추가 등록 및 내 정보 수정 로직 수정
  src/assets/apis/authApi.js
  src/pages/MyInfo/MyInfoEdit.jsx
  src/pages/MyInfo/RegisterDog.jsx
Labels: 🐛 bug fix, ⚙️ chore, 🔧 refactor

#35 fix: #15 회원가입 시 프로필 사진 등록 추가
  src/pages/SignUp/SignUp1.jsx
  src/pages/SignUp/SignUp2.jsx
Labels: 💡 feat

#38 Fix: 내가 등록한 강아지 내 정보 페이지에서 확인할 수 있도록 수정
  src/App.jsx
  src/components/Info/DogInfo.jsx
  src/pages/Chat/ChatList.jsx
  src/pages/MyInfo/MyInfoMain.jsx
  src/pages/Walk/WalkDetail.jsx
Labels: 🐛 bug fix, 🎨 design, 💡 feat

#41 Feat: #40 산책 정보, 현황 페이지 기능 추가 및 수정
  src/App.jsx
  src/apis/geolocation.js
  src/apis/getBoringDogs.js
  src/assets/icons/icon-tag-filtering.png
  src/assets/icons/social-login/icon-google.png
  src/assets/icons/social-login/icon-kakao.png
  src/assets/icons/social-login/icon-naver.png
  src/assets/images/orangelogo.png
  src/components/Button/MapInfoButton.jsx
  src/components/Button/MapStatusButton.jsx
  src/components/Button/TagFilteringButton.jsx
  src/components/Header/Header.jsx
  src/components/Info/DogInfo.jsx
  src/components/Map/Map.jsx
  src/components/Tag/Tag.jsx
  src/components/Tag/tagsData.json
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/Map/TagFiltering.jsx
  src/pages/MyInfo/MyInfoMain.jsx
  src/pages/MyInfo/RegisterDog.jsx
  src/pages/TopUp.jsx
Labels: 🎨 design, 🔧 refactor, 💡 feat

#44 feat, fix. refactor: #40 렌더링 관련 문제 해결 및 api 호출 수정과 분리, 태그 필터링된 페이지
  src/apis/authApi.js
  src/apis/geolocation.js
  src/apis/getUserInfo.js
  src/apis/kakaoApi.js
  src/components/Info/DogInfo.jsx
  src/hooks/useKakaoMap.js
  src/pages/Map/MapInfo.jsx
  src/pages/Map/MapStatus.jsx
  src/pages/Map/TagFiltering.jsx
  src/pages/MyInfo/MyInfoMain.jsx
  src/pages/MyInfo/RegisterDog.jsx
Labels: 🐛 bug fix, 🔧 refactor, 💡 feat

#49 Feat: 산책로 추천 및 저장 기능 구현
  src/apis/trail.js
  src/assets/icons/icon-Bookmark1.png
  src/assets/icons/icon-Bookmark2.png
  src/assets/icons/icon-Flag.png
  src/components/Trail/RecommendedTrail.jsx
  src/components/Trail/SavedTrail.jsx
  src/components/Trail/Trail.jsx
  src/pages/Walk/WalkDetail.jsx
Labels: 💡 feat

#48 Feat #47 소셜 로그인 구현
  src/App.jsx
  src/pages/Login.jsx
  src/pages/SignUp/SignUp1.jsx
  src/pages/SignUp/SignUp2.jsx
  src/pages/SocialLogin/GoogleAuth.jsx
  src/pages/SocialLogin/KakaoAuth.jsx
  src/pages/SocialLogin/NaverAuth.jsx
Labels: 💡 feat

#59 Feat: #58 업적 조회 및 칭호 설정, 리팩토링
  src/App.jsx
  src/apis/achievement.js
  src/apis/getDogInfo.js
  src/apis/searchByTag.js
  src/apis/walk.js
  src/assets/icons/icon-dogEmoji.png
  src/components/Dog/DogInfoWalkRecord.jsx
  src/pages/Home.jsx
  src/pages/Map/TagFiltering.jsx
  src/pages/MyInfo/GoalStatus.jsx
  src/pages/MyInfo/GoalsStatus.jsx
  src/pages/MyInfo/MyInfoMain.jsx
  src/pages/MyInfo/RecordMyDogWalk.jsx
  src/utils/getDistance.js
Labels: 🎨 design, 🔧 refactor, 💡 feat

#60 feat: #16 #40 강쥐 오버레이 툴팁 구현
  src/App.jsx
  src/apis/updateDogStatus.js
  src/components/Button/ToggleButton.jsx
  src/components/Dog/DogMoreInfo.jsx
  src/components/Map/Map.jsx
  src/components/SocialLogin/SocialLogin.jsx
  src/components/Walk/SelectRoute.jsx
  src/hooks/useKakaoMap.js
  src/pages/Chat/ChatRoom.jsx
  src/pages/Map/MapInfo.jsx
  src/pages/Map/MapStatus.jsx
Labels: 🎨 design, 💡 feat

#67 Feat/header-meong
  src/apis/meong.js
  src/components/Header/Header.jsx
  src/pages/TopUp.jsx
Labels: 💡 feat

#68 test: #61 유저 채팅방 입장 웹소켓 서버 연결 테스트
  src/apis/authApi.js
  src/pages/Chat/ChatRoom.jsx
Labels: 🤔 test

#69 Refactor/map and err
  src/assets/icons/icons-loading.gif
  src/components/AchievementCategory/AchievementCategory.jsx
  src/components/Message/Message.jsx
  src/components/MessageList/MessageList.jsx
  src/components/Trail/RecommendedTrail.jsx
  src/components/Trail/SavedTrail.jsx
  src/components/Trail/Trail.jsx
  src/hooks/useKakaoMap.js
  src/pages/Map/MapInfo.jsx
  src/pages/Map/TagFiltering.jsx
  src/pages/MyInfo/GoalStatus.jsx
  src/pages/Walk/WalkDetail.jsx
Labels: 🔧 refactor, 💡 feat

#70 Feat: #63 산책 시작전, 산책중, 산책완료 페이지 구현
  src/components/Map/Map2.jsx
  src/hooks/useNewMap.js
  src/pages/Map/MapStatusComplete.jsx
  src/pages/Map/MapStatusStart.jsx
  src/pages/Map/MapStatusWalking.jsx
Labels: 💡 feat

#74 feat: #61 채팅방 생성 및 입장 코드 수정
  src/App.jsx
  src/apis/chatApi.js
  src/components/Dog/DogMoreInfo.jsx
  src/pages/Chat/ChatList.jsx
  src/pages/Chat/ChatRoom.jsx
  src/pages/Map/TagFiltering.jsx
Labels: 💡 feat

#75 Feat: #42 산책로 추천 페이지 (챌린지)
  src/apis/getChallenge.js
  src/assets/icons/icon-footprint.png
  src/assets/icons/icon-speaker.png
  src/assets/icons/icon-walking2.png
  src/pages/Walk/WalkDetail.jsx
Labels: 🔧 refactor

#76 feat: 내 정보 및 강아지 산책기록 페이지 디자인 수정
  src/components/Dog/DogInfo.jsx
  src/pages/MyInfo/MoreRecordMyDogWalk.jsx
  src/pages/MyInfo/MyInfoMain.jsx
  src/pages/MyInfo/OwnerReview.jsx
  src/pages/MyInfo/RecordMyDogWalk.jsx
Labels: 🎨 design

#77 feat: #45 #66 굿즈샵 페이지 구현 및 헤더 수정
  src/App.jsx
  src/apis/goodsApi.js
  src/assets/icons/icon-cart.png
  src/assets/icons/icon-footprint-white.png
  src/assets/icons/icon-search.png
  src/assets/icons/icon-shop.png
  src/components/Goods/Goods.jsx
  src/components/Header/Header.jsx
  src/components/Input/Input.jsx
  src/pages/MeongShop/MeongShop.jsx
  src/pages/MeongShop/MyGoods.jsx
Labels: 🎨 design, 🔧 refactor, 💡 feat

#79 feat: #61 채팅방 생성 및 입장 api 엔드포인트 변경
  src/apis/chatApi.js
  src/components/Dog/DogMoreInfo.jsx
  src/pages/Chat/ChatRoom.jsx
Labels: 💡 feat

#80 fix: #58 대표 업적 설정 부분 수정
  src/App.jsx
  src/apis/achievement.js
  src/components/Achievement/Achievement.jsx
  src/pages/MyInfo/GoalStatus.jsx
Labels: 🐛 bug fix

#82 feat: #40 #42 #61 산책 현황 및 산책로, 채팅방 일부 기능 구현
  src/apis/chatApi.js
  src/apis/getChallenge.js
  src/assets/hooks/useForm.jsx
  src/components/Chat/Chat.jsx
  src/components/Dog/DogMoreInfo.jsx
  src/hooks/useKakaoMap.js
  src/hooks/useUserMap.js
  src/pages/Chat/ChatList.jsx
  src/pages/Chat/ChatRoom.jsx
  src/pages/Map/MapStatusUser.jsx
  src/pages/SignUp/SignUp1.jsx
  src/pages/SignUp/SignUp2.jsx
  src/pages/Walk/WalkDetail.jsx
Labels: 🐛 bug fix, 🎨 design, 🔧 refactor, 💡 feat

#85 feat: 채팅 onmessage로 받아오는 메시지 messages 형식으로 통일
  src/apis/chatApi.js
  src/apis/updateDogStatus.js
  src/components/Dog/DogMoreInfo.jsx
  src/pages/Chat/ChatList.jsx
  src/pages/Chat/ChatRoom.jsx
  src/pages/Map/MapStatusUser.jsx
  src/pages/Map/TagFiltering.jsx
Labels: 💡 feat

#95 Feat #92 MapStatus에서 강아지 띄우기 + ownerEmail, walkUserEmail 불러오게 설정
  src/apis/getDogInfo.js
  src/components/Map/MapUser.jsx
  src/pages/Map/MapStatus.jsx
  src/pages/Map/MapStatusUser.jsx
Labels: 🐛 bug fix, 💡 feat

#96 Design: 로그아웃 기능 추가 및 사용자를 위한 UI 디자인 개선 등
  src/apis/getChallenge.js
  src/components/Button/LogoutButton.jsx
  src/components/Dog/DogMoreInfo.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/MyInfo/MyInfoMain.jsx
  src/pages/Walk/WalkDetail.jsx
Labels: 🎨 design, 🔧 refactor, 💡 feat

#97 fix: #92 태그 필터링 페이지에서 채팅방 접속처리 수정
  src/pages/Map/TagFiltering.jsx
Labels: 🐛 bug fix

#100 Feat: #99 캘린더 만들기
  package-lock.json
  package.json
  src/assets/icons/icon-calender.png
  src/calendarStyles.css
  src/components/Calendar/Calendar.jsx
  src/components/Reservation/Reservation.jsx
  src/pages/Chat/ChatRoom.jsx
Labels: 💡 feat

#98 feat: #92 채팅방 프사 추가 및 읽었는 지 조회 가능하도록 추가
  package-lock.json
  package.json
  src/apis/chatApi.js
  src/components/Chat/Chat.jsx
  src/pages/Chat/ChatList.jsx
Labels: 🐛 bug fix, 🎨 design

#102 Fix, Feat: 채팅방 기능 추가 구현 및 강아지 마커 버그 수정
  src/apis/chatApi.js
  src/components/Chat/Chat.jsx
  src/components/Footer/Footer.jsx
  src/components/Image/Image.jsx
  src/hooks/useForm.js
  src/hooks/useKakaoMap.js
  src/index.js
  src/pages/Chat/ChatList.jsx
  src/pages/Chat/ChatRoom.jsx
  src/pages/Map/MapStatusUser.jsx
  src/pages/MyInfo/MyInfoMain.jsx
  src/pages/MyInfo/OwnerReview.jsx
  src/pages/SignUp/SignUp2.jsx
  src/pages/Walk/WalkDetail.jsx
  src/utils/time.js
Labels: 🐛 bug fix, 🎨 design, 💡 feat
