Repository likelion-inha-hackathon-2/Meong-Signal-FE, pull requests merged in 2024-08, with the labels that each got.

#105 feat: #93 약속 api 시간 형식 수정 및 예약 확인 기능 구현
  src/components/Calendar/Calendar.jsx
  src/components/Reservation/Reservation.jsx
  src/components/Schedule/Schedule.jsx
  src/pages/Chat/ChatRoom.jsx
Labels: 💡 feat

#111 fix: #102 리뷰 조회 에러 수정 및 멍 선물 안 할 수 있도록 설정
  src/pages/MyInfo/OwnerReview.jsx
  src/pages/MyInfo/ReviewReceived.jsx
  src/pages/MyInfo/UserReview.jsx
Labels: 🐛 bug fix

#112 refactor: 버튼 개수가 dom으로 직접 전달되지 않도록 수정
  src/components/Reservation/Reservation.jsx
Labels: 🔧 refactor

#113 refactor: #99 캘린더 및 스케줄 컴포넌트와 툴팁 닫히도록 수정
  src/components/Calendar/Calendar.jsx
  src/components/Chat/Chat.jsx
  src/components/Schedule/Schedule.jsx
  src/pages/Chat/ChatList.jsx
Labels: 🎨 design, 🔧 refactor

#114 fix: #101 움직인 경로가 빨간 선으로 표시되도록 수정
  src/hooks/useUserMap.js
Labels: 🐛 bug fix

#115 fix: #101 움직인 경로가 빨간 선으로 표시되도록 수정
  src/hooks/useUserMap.js
Labels: 🐛 bug fix

#116 fix: #101 움직인 경로가 빨간 선으로 표시되도록 수정 3차
  src/hooks/useUserMap.js
Labels: 🐛 bug fix

#117 design: #101 사용가 ui를 위한 디자인 및 리팩토링 작업
  src/components/Reservation/Reservation.jsx
  src/components/Reservation/ReservationList.jsx
  src/components/Walk/WalkItem.jsx
  src/hooks/useUserMap.js
  src/pages/Chat/ChatList.jsx
  src/pages/Chat/ChatRoom.jsx
  src/pages/Map/MapStatusUser.jsx
  src/pages/Map/TagFiltering.jsx
  src/pages/MyInfo/MyWalk.jsx
Labels: 🐛 bug fix, 🎨 design, 🔧 refactor

#118 Feat: #99 캘린더 구현
  package-lock.json
  package.json
  src/calendarStyles.css
  src/components/Calendar/Calendar.jsx
  src/components/Schedule/Schedule.jsx
  src/pages/Chat/ChatRoom.jsx
Labels: 🎨 design, 🔧 refactor

#119 feat: #99 캘린더 및 약속 컴포넌트 병합
  package-lock.json
  package.json
  src/calendarStyles.css
  src/components/Calendar/Calendar.jsx
  src/components/Schedule/Schedule.jsx
  src/pages/Chat/ChatRoom.jsx
Labels: ⚙️ chore, 🎨 design, 🔧 refactor, 💡 feat

#120 design: #101 채팅창 메시지 버블 길어져도 프사 비율 변하지 않도록 수정
  src/pages/Chat/ChatRoom.jsx
Labels: 🎨 design

#121 Feat: #101 강아지 마커 한번만 뜨도록 설정
  src/hooks/useUserMap.js
Labels: 🐛 bug fix
